name: Update flake.lock

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  lockfile:
    name: Update lockfile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses:  DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/update-flake-lock@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pr-title: "Update flake.lock"
          pr-labels: ci
