users:
    vini:
        password: ENC[AES256_GCM,data:BZQ0L/SmpESX1uJd6XO2Y7ZiOGDjW40fs8CQG4sOAko=,iv:EycvtiJ6twnEoAkCKBswEEEzvuK3NujcP436K8h5s78=,tag:aRWsm2+Tr0QRtUwjtaaH7w==,type:str]
services:
    step-ca:
        root-cert: ENC[AES256_GCM,data:dnGML/xFsJU84Y6LxATa6JNgkeYbBsty+CZPRSLuIOq/ZDdcarHoYjprHGBWr4ypR+AmzpIV/bUoF8Godjms6MHVymrdKi3ErxOuzK5HeLHqwrhxRkGu4LsqmjwkOr/11MPshBf11rx7Cz2C1h4p6CeXWPg+nBCw5qIz1D2cAbJ27eTvCku3wLf97vYOVmFPgTvv0o8lNoOxOIM47HU0cTJcVzK79lxxZuu5TjENtR3omXIzJRwoc+sJvEvQ5A/o4GnTrhBWo22Z0Uut7WIpcSnIoJlOzDHp9Tw1Hel4z+fbJeeT7I354sEmf9KIHqCLjOrumR7brvjP/gvlcFp02BNQEDf01Onr3A2vr4pOKPbHAN/6EzULLC/z3G+IQ5IiHPGjdTrE+MRZCkxD/Ii5t55A4pthrOFemwXpDJ/ahRGRTgFeSAHzL4Ga2EXVrW04wRE3FzeplfEc475pJ+cR6L4cQ1H4/cdUZ0+zGJOfOreySZnhjdZjXCiRvs6UWbkLsAtGq8OB1S3IcMuHreyh5PQpLjE1Pi9DO/8pLvX9EVVp7B9hkhztagkHpRfRd/rXZaxqdstsC0tnRubVctNjo33P80x0p1b1HXmTsN2nU+oU1OqI4WvrIwadBUlhQ0jVELFvNB9E2eghOvAdtYkDq2YwXXgJ9A9uVWhk1mL/VmE7nBOhe4trNkivrvFfoq6WH8WEfXosK1Dcln1YoINwqYTbDRjl6qtKOnXFfjppZiyjSZlnGt5QRRPC88hm8PD0q7p5DPbFiV4/OCwq2SnO9KjeKshvFTw+HqiXX+clIComC3vXWhaBbIrGa/mlUgargvSk,iv:Cj6E3BnuZZSMW7H1GB775To4uzop90fettpSbfnodIQ=,tag:u4PuNMpPbtUbY7gkr56bfg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age187qq0tg2d7pzs0nf9xhqp4j28feztsn5qzcvsamepnysa8duhqgqwm53es
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1VnpZUEwrL0QyaU5nWDI5
            b0lidWpSdFRTNDl4N1dlby9VUEdINVdNWUFvCnVMdUcrRWZPV3k5RXB4K0NDeG5p
            dnVyVDJGemdtUW5BUkQvelpCeHVRclkKLS0tIFVHVk5HcmhBUUZKbWxlNGNSb1RJ
            QmZHdWZDQlJMenlzUlVqb3VPbGRkTTgKpJ18vG4gZoERvu1cRZJQqIA8Ntff08RO
            VYLAH1Q+ikXUTqZnv6HCvQ6Ujavzwhs3/d+aWxfqjKpTrDPRGKhAjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-16T22:34:30Z"
    mac: ENC[AES256_GCM,data:D+pKUvHv6oFUBgmzWNZSeWtcS7AeJSFxs+gsld9AQZAX5t/HMPW/Di8oXnlbpsLQ82ov7eWiCMD30X7rx1T49nib3vy8W5PIEp8bkH+gm40NYpeio++uC+vW7jDUydmQrzzA1lOYzk6LtwuAWeM/3O2VLUegmYBXW/2r8hmkx3g=,iv:2gtW+0fa7jgWANfI2kx7ssOH2P6gv5Y3jgIrXqFWRy8=,tag:/SSKTeDsuBiOa8qphyRKOg==,type:str]
    pgp:
        - created_at: "2024-01-15T20:18:07Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DPwdqFE4beygSAQdAsPGzfEU+DaXPOWudUSO/W3rAWWSxVct8+b7JDiWKpwgw
            1gkTKR81f5GcVLg2b4b30RYcGqFp11fO6pgp81zBCBypFjgtSA1jfTeDfkZcps2P
            0l4BryeTFbaFajWEPwvUB9XxqvDgl+PeAxFzPWHXPC+FrY2Yy1ICI3kjCsYPiqBj
            him5Y21n7xFlT/WaCNilDzHEPNQIi8bvcLZ/ORl3NUQrO/Po6GLg7/CfpkQvjCNq
            =HDs0
            -----END PGP MESSAGE-----
          fp: 2241DDE7BE678A7EB70377F43F076A144E1B7B28
    unencrypted_suffix: _unencrypted
    version: 3.8.1
