users:
    vini:
        password: ENC[AES256_GCM,data:BZQ0L/SmpESX1uJd6XO2Y7ZiOGDjW40fs8CQG4sOAko=,iv:EycvtiJ6twnEoAkCKBswEEEzvuK3NujcP436K8h5s78=,tag:aRWsm2+Tr0QRtUwjtaaH7w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age187qq0tg2d7pzs0nf9xhqp4j28feztsn5qzcvsamepnysa8duhqgqwm53es
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByWTc0ekFlRi93SFZoTVF2
            Qmt1TkdMYzBEVmlUSURYY1BJWGcyeThRUWtBCjZUdUVUVk50RGpBSW41L1ZVcDZv
            MVdOaVBSTCs1RUtZSmZhcmk1MzhRSEkKLS0tIHhISmJjc1NVeWNnODQyZzZBYnZL
            RVl5clRLSVNwOHhJczFNaUM0cFBvczQKr5bG4Agk0Cq0OvfSIu1kW7r1Dr2ZJxZk
            jJWxWVp16JEpaRuKTd4GIN08hCsBu85vi/tjlTli4VBAxOVZSbxvSQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1p7z2hzrh6cywxy9xv042ev926eplwzvs2zy8rccj8hdeatnngu7s5acpyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQWDZSVTR3VzZabDFCVS9Y
            TmpPRHpFTnhWT1Z5eS9WYVhXa1R2VU5PY0ZvClRqYTJoQ3lsaXcyMHJHL1BVRFZB
            enVwWkRoWTNoVkpwemlYSks5RW00V28KLS0tIFp2UUl0bFpEbEp1VllkU3ppVjJR
            dDBZTHVLSVFZYTQ5ZTdyUUM5WGIxbWMKFTO/PLoWtsp3OksJ8XqIxDWvtSzYs5mv
            QdGwzIqWA0mxQ/1CVvaxaIngBt8n9+0cupZK96qcgEp7A0hE4fNX9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-16T22:59:10Z"
    mac: ENC[AES256_GCM,data:BoJs3ADV+Q72qvPH02k0bgz7DPC6oLf2SCnC5ceAIb9ZUsHf/UobbvEA7CNMrUzz6D28iUTnWAcvRAXdlHiTySu2gL/U/AhIjtG5Q9UWfz44qzMV8p8C+7wZWC1BAvb9Fbse+RewlNh6TO3NcQbFbs1Ye6024uow7ddbfB3dB4Y=,iv:BGOl7rU9H5RMAZk6GZeuLDdJa6G6/2jlXT21/1jPMJk=,tag:taTUZvWRhY4Xcq3Nq81n6w==,type:str]
    pgp:
        - created_at: "2024-05-04T00:30:34Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DPwdqFE4beygSAQdAJGzISC64VBmTQdTD6/ShW1Buy16uWNEhfDn0jqiVEUIw
            MgGa54EvNvBcU+zoLPmRhX2Qc2JKYVYvzJWQj+8h9YGG9yVdMcghMFx51DKTzzqa
            0l4BUIxngbjfyIfi1KZ6eDpRqHa8CfXngTuuXTri8fmUBWQKkSz/vpL1Zj0SEVSC
            ZIQs5KO7KyxTA3wUBP8K7+8XMtH4uIY7RngMUiZuSpjAQr+tFiRCvyzkoinwQmpO
            =ZVnI
            -----END PGP MESSAGE-----
          fp: 2241DDE7BE678A7EB70377F43F076A144E1B7B28
    unencrypted_suffix: _unencrypted
    version: 3.8.1
