users:
    vini:
        password: ENC[AES256_GCM,data:BZQ0L/SmpESX1uJd6XO2Y7ZiOGDjW40fs8CQG4sOAko=,iv:EycvtiJ6twnEoAkCKBswEEEzvuK3NujcP436K8h5s78=,tag:aRWsm2+Tr0QRtUwjtaaH7w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age187qq0tg2d7pzs0nf9xhqp4j28feztsn5qzcvsamepnysa8duhqgqwm53es
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1VnpZUEwrL0QyaU5nWDI5
            b0lidWpSdFRTNDl4N1dlby9VUEdINVdNWUFvCnVMdUcrRWZPV3k5RXB4K0NDeG5p
            dnVyVDJGemdtUW5BUkQvelpCeHVRclkKLS0tIFVHVk5HcmhBUUZKbWxlNGNSb1RJ
            QmZHdWZDQlJMenlzUlVqb3VPbGRkTTgKpJ18vG4gZoERvu1cRZJQqIA8Ntff08RO
            VYLAH1Q+ikXUTqZnv6HCvQ6Ujavzwhs3/d+aWxfqjKpTrDPRGKhAjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-16T22:59:10Z"
    mac: ENC[AES256_GCM,data:BoJs3ADV+Q72qvPH02k0bgz7DPC6oLf2SCnC5ceAIb9ZUsHf/UobbvEA7CNMrUzz6D28iUTnWAcvRAXdlHiTySu2gL/U/AhIjtG5Q9UWfz44qzMV8p8C+7wZWC1BAvb9Fbse+RewlNh6TO3NcQbFbs1Ye6024uow7ddbfB3dB4Y=,iv:BGOl7rU9H5RMAZk6GZeuLDdJa6G6/2jlXT21/1jPMJk=,tag:taTUZvWRhY4Xcq3Nq81n6w==,type:str]
    pgp:
        - created_at: "2024-01-15T20:18:07Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DPwdqFE4beygSAQdAsPGzfEU+DaXPOWudUSO/W3rAWWSxVct8+b7JDiWKpwgw
            1gkTKR81f5GcVLg2b4b30RYcGqFp11fO6pgp81zBCBypFjgtSA1jfTeDfkZcps2P
            0l4BryeTFbaFajWEPwvUB9XxqvDgl+PeAxFzPWHXPC+FrY2Yy1ICI3kjCsYPiqBj
            him5Y21n7xFlT/WaCNilDzHEPNQIi8bvcLZ/ORl3NUQrO/Po6GLg7/CfpkQvjCNq
            =HDs0
            -----END PGP MESSAGE-----
          fp: 2241DDE7BE678A7EB70377F43F076A144E1B7B28
    unencrypted_suffix: _unencrypted
    version: 3.8.1
